# @see https://github.com/integratedexperts/drupal_circleci
version: 2
aliases:
  # Replace the SSH deployment key fingerprint value below with your own.
  # Get it from CircleCI App -> Project -> Settings -> SSH Permissions.
  - &deploy_ssh_fingerprint "2d:71:4d:aa:4d:34:38:b5:8f:af:ca:3b:d4:82:6a:21"
  - &container_config
    working_directory: ~/project
    docker:
      - image: circleci/php:7.3-cli-browsers
    environment:
      DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint

job-build: &job-build
    steps:
      - checkout
      - run: sudo -E apt-get update && sudo -E apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev && sudo -E docker-php-ext-install -j$(nproc) iconv && sudo -E docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && sudo -E docker-php-ext-install -j$(nproc) gd
      - run: .circleci/build.sh
      - run: .circleci/test.sh
      - run:
          command: .circleci/process-artifacts.sh
          when: always
      - store_test_results:
          path: /tmp/test_results
          when: always
      - store_artifacts:
          path: /tmp/artifacts
          when: always

jobs:
  build-php-7.3:
    <<: *container_config
    <<: *job-build

  build-php-7.2:
    <<: *container_config
    docker:
      - image: circleci/php:7.2-cli-browsers
    <<: *job-build

  deploy:
    <<: *container_config
    environment:
      DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - *deploy_ssh_fingerprint
      - run: DEPLOY_BRANCH=${CIRCLE_BRANCH} .circleci/deploy.sh

workflows:
  version: 2
  main:
    jobs:
      - build-php-7.3:
          filters:
            tags:
              only: /.*/
      - build-php-7.2:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build-php-7.3
            - build-php-7.2
          filters:
            tags:
              only: /.*/
            branches:
              # 7.x, 8.x, 7.x-1.x, 8.x-1.x, 7.x-2.x, 8.x-2.x, ci
              only: /^(?:7|8)\.x(?:\-[0-9]+\.x)?|ci$/
