name: Release docs

on:
  push:
    tags:
      - '*'
      - '1.x'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  release-docs:
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .scaffold/docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: '${{ github.workspace }}/.scaffold/docs'

      - name: Build documentation site
        run: npm run build
        working-directory: '${{ github.workspace }}/.scaffold/docs'

      - name: Setup GitHub pages
        uses: actions/configure-pages@v5
        id: pages

      - name: Upload documentation site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ".scaffold/docs/build"

      - name: Deploy documentation site
        uses: actions/deploy-pages@v4
